name = "agentsweb"
main = "src/index.ts"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = false

[[routes]]
pattern = "agentsweb.org"
custom_domain = true

[[routes]]
pattern = "api.agentsweb.org"
custom_domain = true

[[kv_namespaces]]
binding = "CACHE"
id = "fa20a13348bf4f0ab7289dbad534ec11"
